# Generated by Django 2.2.7 on 2019-11-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(default='', max_length=12)),
            ],
            options={
                'db_table': 'test_model',
            },
        ),
    ]
