# Generated by Django 2.2.7 on 2019-11-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='主键id'),
        ),
    ]
