# Generated by Django 2.2.7 on 2019-11-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191112_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='pwd',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='role',
            field=models.IntegerField(default=1),
        ),
    ]
