# Generated by Django 2.2.7 on 2019-11-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191112_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='123456', max_length=12),
        ),
    ]
