# Generated by Django 2.1.8 on 2020-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoPro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键id')),
                ('name', models.CharField(default='123456', max_length=12)),
            ],
            options={
                'db_table': 'django_pro',
            },
        ),
    ]
